### ISSUE TITLE
[Bug] Uncaught error: `Header must provide a Content-Length property.`

### ISSUE THREAD

**Issue by nschmeller** [tilt-dev/vscode-tilt#34]
I got this error when installing the extension:

<img width="872" alt="image" src="https://user-images.githubusercontent.com/26189705/228630650-71771927-d2dd-4eb3-b753-1b8fbbfceea8.png">

This appears to be a bug in the extension. When I mouse over any syntax in my Tiltfile, I get a tooltip that only says "Loading...", and when I check the "Runtime Status" again, I see a few more `Header must provide a Content-Length property.` uncaught errors. 

<img width="276" alt="image" src="https://user-images.githubusercontent.com/26189705/228630912-6d5fefd5-1962-4cf6-befd-3c93890e8517.png">

Is there anything I can do as a fix or workaround? Thanks!

**Comment by nicksieger** [comment]
- What version of Tilt do you have installed?
- Can you try running the `tiltfile.restartServer` command from the command palette?
- What do you see when going to the VS Code output pane and selecting the "tiltfile" output pane? For example, I see
```
[Info  - 2:04:40 PM] Tiltfile LSP started
[Info  - 2:04:40 PM] Found Tilt version 0.32.0-dev
[Info  - 2:04:40 PM] Starting child process
Error: No tilt apiserver found: tilt-default

No running Tilt found. Tiltfile runtime error highlighting will work when Tilt is started.
tilt session watch exited w/ code 1
Starlark LSP server initialized
[Info  - 2:06:24 PM] Restarting server
[Info  - 2:06:24 PM] Tiltfile LSP started
[Info  - 2:06:24 PM] Found Tilt version 0.32.0-dev
[Info  - 2:06:24 PM] Starting child process
Starlark LSP server initialized
```

**Comment by nschmeller** [comment]
Hmm, I just checked again, and now the extension is working. 

In the time between filing this bug and writing this comment, I switched from Minikube v1.25 to v1.29, so maybe that had something to do with it. 

If this error happens again I'll comment here, but for now I'll close this issue. Thanks for the help!!

**Comment by gebinic** [comment]
I'm facing this issue on Debian 12, k3d v5.8.3 (k3s: v1.31.5-k3s1) and Tilt 0.34.0. "Restart Tiltfile LSP Server" is loading for ever.

"tiltfile" output pane log:
```bash
[Info  - 10:18:26 AM] Tiltfile LSP started
Error: No tilt apiserver found: tilt-default

No running Tilt found. Tiltfile runtime error highlighting will work when Tilt is started.
tilt session watch exited w/ code 1
[Info  - 10:18:26 AM] Found Tilt version 0.34.0
[Info  - 10:18:26 AM] Starting child process
Starlark LSP server initialized
[Info  - 10:42:41 AM] Restarting server
```
