### ISSUE TITLE
[Feature] Add support for changing search file name

### ISSUE THREAD

**Issue by Tohusk** [tilt-dev/vscode-tilt#35]
Based on [the FAQs](https://docs.tilt.dev/faq.html#q-when-i-run-tilt-version-i-see-template-engine-not-found-for-version-what-do-i-do), people who have installed rbenv or something similar may have followed the FAQs and renamed the tilt binary to tlt. However, this extension seems to only look for binaries under the name Tilt, which causes the following error:
![image](https://user-images.githubusercontent.com/33451949/233510372-213705ae-be50-4bee-9c8a-04a091ddc70e.png)

**Comment by nicksieger** [comment]
Hi, thanks for the feedback. The extension has a setting where you can specify the full path to the actual Tilt executable.

![Cursor_and_Settings_and__emacs_mg9j9p4vq4_-___Users_nicksieger_tilt-dev_vscode-tilt_src_config_ts_](https://user-images.githubusercontent.com/154/233656398-078220e9-429a-49b8-bd8d-475c096436f7.png)

It goes in the `settings.json` preference file.

![Cursor_and_Notification_Center](https://user-images.githubusercontent.com/154/233656664-d11eb437-48ca-4f96-93e5-ce4d815e99bb.png)

It should work to also just put `tlt` there too, without a full path. Does that work for your problem?

**Comment by Tohusk** [comment]
Oh yeah that fixes it thank you!
